version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: payzap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payzap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - payzap-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payzap" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: payzap-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - payzap-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Express Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payzap-backend
    restart: unless-stopped
    environment:
      # NODE_ENV: production
      PORT: 5000
      # Database connection
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/payzap
      # Redis connection
      REDIS_URL: redis://redis:6379
      # JWT Secret
      # JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      # Optional: Additional environment variables
      # CORS_ORIGIN: http://localhost:3000
      JWT_SECRET: gkuxy@295mdlq
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - payzap-network
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  payzap-network:
    driver: bridge
